package com.generic.selector;

public class SearchResultSelectors {
	public static final String searchInput = "js-site-search-input";
	public static final String searchBtn = "btn btn-link js_search_button";
	public static final String nthResponsiveListItemListLink = ".ui-menu.ui-widget.ui-widget-content.ui-autocomplete.ui-front>.ui-menu-item a:eq(1)";
	public static final String nthResponsiveListItemColumn = ".ui-menu.ui-widget.ui-widget-content.ui-autocomplete.ui-front>.ui-menu-item>a :eq({0})";
	public static final String nthResponsiveListItemListImg = "css,.ui-menu.ui-widget.ui-widget-content.ui-autocomplete.ui-front>.ui-menu-item>a>div>img";
	
	public static final String 	searchMenuItems = "ui-menu-item";
	public static final String 	searchMenuItems_Link = "ui-menu-item-wrapper";
	public static final String 	searchMenuItems_Name = "name";
	public static final String 	searchMenuItems_Price = "price";
	public static final String 	searchMenuItems_Image = "img";
	public static final String 	searchResultsHeader = "results";
	public static final String 	searchResultsHeaderSearchEmpty = "headline";
	public static final String 	searchResultsContinueShopping = "btn btn-default  js-shopping-button";
	public static final String sortOptions1 = "sortOptions1";
	public static final String sortOptions2 = "sortOptions2";
	public static final String numberOfProductsFound = "test_searchResults_productsFound_label_$2";
	public static final String productItem = "product-item";
	public static final String shopByStore = "Shop by Stores";
	public static final String userLocationStore = "user_location_query";
	public static final String findStoresNearMeAjax = "findStoresNearMeAjax";
	public static final String addToCartForm = "addToCartForm";
	public static final String productPickupInStoreButton = "product_";
	public static final String moreStores = "js-more-stores-facet-values";
	public static final String plpProductPriceLabel = "test_searchPage_price_label_{0}_$1";
	public static final String addToCartItemPriceParent = "add-to-cart-item";
	public static final String addToCartItemPrice = "price";
	public static final String addToCartItemCheckoutBtn = "test_checkoutLinkInPopup_$2";
	public static final String addToCartItemContinueShoppingBtn = "Continue Shopping";
	public static final String cboxCloseBtn = "cboxClose";
	public static final String facetNavTitleStores = "test_facetNav_title_Stores_$1";
	public static final String facetNavTitlePrice = "test_facetNav_title_Price_$1";
	public static final String facetNavTitleColour = "test_facetNav_title_Colour_$1";
	public static final String facetNavTitleSize = "test_facetNav_title_Size_$1";
	public static final String facetNavSecondCount = "test_facetNav_count_$2";
	public static final String facetNavThirdCount = "test_facetNav_count_$3";
	public static final String changeLocationLink = "js-facet-change-link";
	public static final String locationFacetContainer = "facet__results js-facet-container";
	public static final String nthProductItem = ".product-item:eq({0})";
	public static final String nthAppliedFacets = ".facet.js-facet .facet__list li a:eq({0})";
	public static final String pickupInStoreLocationSearch = "locationForSearch";
	public static final String pickupNthAccessibleTabIcon = "accessibletabsnavigation0-{0}";
	public static final String pickupInStoreList = "pickup-store-list-entry";
	public static final String pickupInStoreProduct = "pickupModal_product_{0}";
	public static final String pickupAddToBagBtn = "js-add-to-cart-for-pickup-popup";
	public static final String pickupDecreaseQtyBtn = "js-qty-selector-minus";
	public static final String pickupIncreaseQtyBtn = "js-qty-selector-plus";
	public static final String pickupQtyInput = "js-qty-selector-input";
}
