package com.generic.setup;

public class ExceptionMsg {
	//@TODO: please add all exception messages 
	public static final String noValidSelector = "selector object was not generated by selutils";
	public static final String noErrorMsg = "No Valid error message found in cart";
}
