package com.generic.setup;

public class ExceptionMsg {
	public static final String noValidSelector = "selector object was not generated by selutils";
	public static final String noErrorMsg = "No Valid error message found in cart";
	public static final String PageFunctionFailed = "<p style='font-weight: bold; color:red'>Page function failed: {0} </p>";

}
